SELECT T_POLICY.*
FROM T_POLICY
JOIN T_CLIENT ON T_POLICY.CLIENT_NUMBER = T_CLIENT.CLIENT_NUMBER
WHERE T_POLICY.POLICY_SUBMIT_DATE > '2018-01-15' AND EXTRACT(MONTH FROM T_CLIENT.BIRTH_DATE) = 9;

SELECT T_POLICY.*
FROM T_POLICY
JOIN T_AGENT ON T_POLICY.AGENT_CODE = T_AGENT.AGENT_CODE
WHERE T_POLICY.POLICY_STATUS = 'Inforce' AND T_AGENT.AGENT_OFFICE = 'Jakarta';

SELECT T_AGENT.AGENT_CODE, (T_POLICY.COMMISSION / T_POLICY.PREMIUM) * 100 AS BASIC_COMMISSION
FROM T_POLICY
JOIN T_AGENT ON T_POLICY.AGENT_CODE = T_AGENT.AGENT_CODE
WHERE T_POLICY.PREMIUM <> 0;

UPDATE T_POLICY
SET POLICY_DUE_DATE = DATE_TRUNC('MONTH', POLICY_SUBMIT_DATE) + INTERVAL '1 MONTH' - INTERVAL '1 DAY';


SELECT P.*, A.AGENT_NAME, A.AGENT_OFFICE
FROM T_POLICY P
JOIN T_AGENT A ON P.AGENT_CODE = A.AGENT_CODE
WHERE (P.PREMIUM - (P.PREMIUM * P.DISCOUNT / 100)) < 1000000
ORDER BY (P.PREMIUM - (P.PREMIUM * P.DISCOUNT / 100)) ASC;

